import { action, component } from "./helpers.js";

export const agentComponents = [
  component({
    id: "desktop.agent.conversation",
    name: "Conversation",
    summary: "Navigates conversation history and verifies message structure.",
    kind: "agent",
    sideEffectLevel: "reversible",
    actions: [action("select", "Select a conversation."), action("startNew", "Start an empty draft conversation.", "reversible")],
    assertions: ["conversationExists", "messageExists", "roleSequenceMatches"],
    locatorKeys: ["conversation.list", "conversation.item", "conversation.message"],
    tags: ["agent", "chat"],
  }),
  component({
    id: "desktop.agent.composer",
    name: "Agent Composer",
    summary: "Edits prompts and submits them through an agent application's composer.",
    kind: "agent",
    sideEffectLevel: "externalEffect",
    requiredCapabilities: ["ui.inspect", "ui.set-value", "ui.invoke"],
    actions: [action("setPrompt", "Set the prompt draft.", "writesLocal"), action("submit", "Submit a prompt to the agent.", "externalEffect"), action("cancelDraft", "Clear the prompt draft.", "reversible")],
    assertions: ["promptEquals", "canSubmit", "isBusy"],
    locatorKeys: ["composer.editor", "composer.submit", "composer.stop"],
    tags: ["agent", "input"],
  }),
  component({
    id: "desktop.agent.streaming-response",
    name: "Streaming Response",
    summary: "Observes generation state and incremental response completion.",
    kind: "agent",
    sideEffectLevel: "readOnly",
    requiredCapabilities: ["ui.inspect", "ui.wait"],
    actions: [action("waitForStart", "Wait for response streaming to begin."), action("waitForCompletion", "Wait for response streaming to complete.")],
    assertions: ["isStreaming", "isComplete", "containsText", "hasError"],
    locatorKeys: ["response.container", "response.streaming", "response.error"],
    requiredFixtures: ["agent.scripted-run"],
    tags: ["agent", "streaming"],
  }),
  component({
    id: "desktop.agent.model-picker",
    name: "Model Picker",
    summary: "Chooses and verifies an available model or execution profile.",
    kind: "agent",
    sideEffectLevel: "writesLocal",
    actions: [action("open", "Open the model picker.", "reversible"), action("select", "Select a declared model.", "writesLocal")],
    assertions: ["modelExists", "selectedModelEquals", "modelIsUnavailable"],
    locatorKeys: ["modelPicker.trigger", "modelPicker.option"],
    tags: ["agent", "configuration"],
  }),
  component({
    id: "desktop.agent.attachment",
    name: "Agent Attachment",
    summary: "Adds, inspects, and removes prompt attachments through native dialogs or drag-drop.",
    kind: "agent",
    sideEffectLevel: "writesLocal",
    requiredCapabilities: ["ui.inspect", "ui.invoke", "system.open-save-panel"],
    actions: [action("addFile", "Add a declared local file.", "writesLocal"), action("remove", "Remove a staged attachment.", "reversible")],
    assertions: ["attachmentExists", "uploadIsComplete", "attachmentHasError"],
    locatorKeys: ["attachment.add", "attachment.item", "attachment.remove"],
    requiredFixtures: ["desktop.filesystem-sandbox"],
    tags: ["agent", "filesystem"],
  }),
  component({
    id: "desktop.agent.tool-call",
    name: "Tool Call",
    summary: "Observes agent tool calls and their deterministic result state.",
    kind: "agent",
    sideEffectLevel: "externalEffect",
    requiredCapabilities: ["ui.inspect", "ui.wait"],
    actions: [action("expand", "Expand tool-call details.", "reversible"), action("retry", "Retry a declared tool call.", "externalEffect")],
    assertions: ["toolWasCalled", "argumentsMatch", "statusEquals", "resultIsShown"],
    locatorKeys: ["toolCall.item", "toolCall.status", "toolCall.result"],
    requiredFixtures: ["agent.tool-fixture", "agent.side-effect-probe"],
    tags: ["agent", "tools"],
  }),
  component({
    id: "desktop.agent.approval",
    name: "Agent Approval",
    summary: "Handles explicit user approval gates around agent actions.",
    kind: "agent",
    sideEffectLevel: "externalEffect",
    requiredCapabilities: ["ui.inspect", "ui.invoke", "ui.wait"],
    actions: [action("approveOnce", "Approve the displayed action once.", "externalEffect"), action("deny", "Deny the displayed action.", "reversible"), action("inspectDetails", "Inspect approval details.", "readOnly")],
    assertions: ["isRequested", "scopeEquals", "riskTextIsShown"],
    locatorKeys: ["approval.prompt", "approval.allowOnce", "approval.deny"],
    requiredFixtures: ["agent.tool-fixture", "agent.side-effect-probe"],
    tags: ["agent", "approval", "security"],
  }),
  component({
    id: "desktop.agent.permission-mode",
    name: "Agent Permission Mode",
    summary: "Reads and changes the agent application's declared execution permission mode.",
    kind: "agent",
    sideEffectLevel: "securitySensitive",
    actions: [action("open", "Open permission-mode controls.", "readOnly"), action("select", "Select a declared permission mode.", "securitySensitive")],
    assertions: ["selectedModeEquals", "modeIsAvailable", "warningIsShown"],
    locatorKeys: ["permissionMode.trigger", "permissionMode.option", "permissionMode.warning"],
    tags: ["agent", "security", "configuration"],
  }),
  component({
    id: "desktop.agent.task-run",
    name: "Agent Task Run",
    summary: "Observes, pauses, resumes, and cancels a long-running agent task.",
    kind: "agent",
    sideEffectLevel: "externalEffect",
    requiredCapabilities: ["ui.inspect", "ui.invoke", "ui.wait"],
    actions: [action("pause", "Pause a running task.", "reversible"), action("resume", "Resume a paused task.", "externalEffect"), action("cancel", "Cancel the task.", "reversible")],
    assertions: ["statusEquals", "progressIsShown", "durationIsShown"],
    locatorKeys: ["taskRun.status", "taskRun.pause", "taskRun.cancel"],
    requiredFixtures: ["agent.scripted-run"],
    tags: ["agent", "task"],
  }),
  component({
    id: "desktop.agent.computer-control",
    name: "Agent Computer Control",
    summary: "Tests the product UI that starts, shows, and stops computer-control sessions.",
    kind: "agent",
    sideEffectLevel: "securitySensitive",
    requiredCapabilities: ["ui.inspect", "ui.invoke", "ui.wait"],
    actions: [action("start", "Start an explicitly scoped control session.", "securitySensitive"), action("stop", "Stop the active control session.", "reversible"), action("showStatus", "Show session status.", "readOnly")],
    assertions: ["isActive", "scopeIsShown", "stopControlIsAvailable"],
    locatorKeys: ["computerControl.start", "computerControl.status", "computerControl.stop"],
    requiredFixtures: ["agent.input-event-probe"],
    tags: ["agent", "computer-control", "security"],
  }),
  component({
    id: "desktop.agent.emergency-stop",
    name: "Agent Emergency Stop",
    summary: "Verifies a user-visible, immediately reachable stop path for active agent work.",
    kind: "agent",
    sideEffectLevel: "reversible",
    requiredCapabilities: ["ui.inspect", "ui.invoke", "ui.wait"],
    actions: [action("trigger", "Trigger the declared emergency stop."), action("waitForIdle", "Wait until agent activity stops.")],
    assertions: ["isReachable", "agentIsIdle", "noFurtherActionsOccur"],
    locatorKeys: ["emergencyStop.control", "emergencyStop.status"],
    requiredFixtures: ["agent.scripted-run", "agent.side-effect-probe"],
    tags: ["agent", "safety", "smoke"],
  }),
  component({
    id: "desktop.agent.session-recovery",
    name: "Agent Session Recovery",
    summary: "Restores interrupted sessions and verifies recovery messaging.",
    kind: "agent",
    sideEffectLevel: "writesLocal",
    requiredCapabilities: ["ui.inspect", "ui.invoke", "ui.wait"],
    actions: [action("restore", "Restore an interrupted session.", "writesLocal"), action("discard", "Discard offered recovery state.", "writesLocal")],
    assertions: ["recoveryIsOffered", "restoredStateMatches", "failureIsExplained"],
    locatorKeys: ["recovery.prompt", "recovery.restore", "recovery.discard"],
    requiredFixtures: ["agent.recovery-state"],
    tags: ["agent", "recovery"],
  }),
  component({
    id: "desktop.agent.artifact",
    name: "Agent Artifact",
    summary: "Opens and verifies files, previews, diffs, or other agent-produced artifacts.",
    kind: "agent",
    sideEffectLevel: "writesLocal",
    actions: [action("open", "Open an artifact preview.", "readOnly"), action("save", "Save an artifact locally.", "writesLocal"), action("reveal", "Reveal an artifact in the file manager.", "reversible")],
    assertions: ["artifactExists", "typeEquals", "previewIsAvailable"],
    locatorKeys: ["artifact.item", "artifact.preview", "artifact.save"],
    requiredFixtures: ["desktop.filesystem-sandbox"],
    tags: ["agent", "artifact", "filesystem"],
  }),
  component({
    id: "desktop.agent.terminal",
    name: "Agent Terminal",
    summary: "Observes terminal sessions embedded in an agent application.",
    kind: "agent",
    sideEffectLevel: "externalEffect",
    requiredCapabilities: ["ui.inspect", "ui.set-value", "keyboard.inject"],
    actions: [action("sendInput", "Send declared terminal input.", "externalEffect"), action("interrupt", "Interrupt the active terminal command.", "reversible"), action("clearView", "Clear terminal presentation.", "reversible")],
    assertions: ["commandIsShown", "outputContains", "exitStatusEquals"],
    locatorKeys: ["terminal.root", "terminal.input", "terminal.output"],
    requiredFixtures: ["agent.command-fixture", "agent.side-effect-probe"],
    tags: ["agent", "terminal", "developer-tool"],
  }),
] as const;
