import { action, component } from "./helpers.js";

export const commonComponents = [
  component({
    id: "desktop.common.app-lifecycle",
    name: "Application Lifecycle",
    summary: "Launches, attaches to, quits, and terminates a desktop application.",
    kind: "common",
    sideEffectLevel: "writesLocal",
    requiredCapabilities: ["app.launch", "app.attach", "app.quit", "app.terminate"],
    actions: [
      action("launch", "Launch an owned application session.", "reversible"),
      action("attach", "Attach to an explicitly allowed session.", "readOnly"),
      action("quit", "Request a normal application quit.", "reversible"),
      action("terminate", "Terminate an owned application process.", "writesLocal"),
    ],
    assertions: ["isRunning", "isNotRunning", "ownsSession"],
    locatorKeys: ["application.root"],
    tags: ["process", "smoke"],
  }),
  component({
    id: "desktop.common.window",
    name: "Window",
    summary: "Inspects and manages application windows through semantic operations.",
    kind: "common",
    sideEffectLevel: "reversible",
    requiredCapabilities: ["window.inspect", "window.manage"],
    actions: [
      action("focus", "Focus a matching window."),
      action("close", "Close a matching window."),
      action("minimize", "Minimize a matching window."),
      action("restore", "Restore a minimized window."),
    ],
    assertions: ["isVisible", "isFocused", "isMinimized", "hasTitle"],
    locatorKeys: ["window.main", "window.secondary"],
    tags: ["window", "smoke"],
  }),
  component({
    id: "desktop.common.menu",
    name: "Application Menu",
    summary: "Opens menus and invokes menu commands without hard-coded coordinates.",
    kind: "common",
    sideEffectLevel: "reversible",
    requiredCapabilities: ["ui.inspect", "menu.invoke"],
    actions: [
      action("openMenu", "Open a menu by semantic path."),
      action("invokeItem", "Invoke an enabled menu item."),
      action("dismiss", "Dismiss the open menu."),
    ],
    assertions: ["itemExists", "itemIsEnabled", "itemIsChecked"],
    locatorKeys: ["menu.root", "menu.item"],
    tags: ["menu", "navigation"],
  }),
  component({
    id: "desktop.common.toolbar",
    name: "Toolbar",
    summary: "Interacts with window toolbars and grouped toolbar controls.",
    kind: "common",
    sideEffectLevel: "reversible",
    requiredCapabilities: ["ui.inspect", "ui.invoke"],
    actions: [action("invokeItem", "Invoke a toolbar item."), action("showOverflow", "Open toolbar overflow items.")],
    assertions: ["itemExists", "itemIsEnabled", "itemIsSelected"],
    locatorKeys: ["toolbar.root", "toolbar.item"],
    tags: ["toolbar", "navigation"],
  }),
  component({
    id: "desktop.common.navigation",
    name: "Sidebar Navigation",
    summary: "Selects destinations in sidebars, outlines, and navigation lists.",
    kind: "common",
    sideEffectLevel: "reversible",
    requiredCapabilities: ["ui.inspect", "ui.invoke", "ui.wait"],
    actions: [action("selectDestination", "Select a semantic navigation destination."), action("expandGroup", "Expand a navigation group.")],
    assertions: ["destinationExists", "destinationIsSelected"],
    locatorKeys: ["navigation.root", "navigation.destination"],
    tags: ["sidebar", "navigation"],
  }),
  component({
    id: "desktop.common.tabs",
    name: "Tabs",
    summary: "Switches and verifies tabs in native tab groups.",
    kind: "common",
    sideEffectLevel: "reversible",
    requiredCapabilities: ["ui.inspect", "ui.invoke"],
    actions: [action("select", "Select a tab."), action("close", "Close a closable tab.")],
    assertions: ["tabExists", "tabIsSelected"],
    locatorKeys: ["tabs.root", "tabs.tab"],
    tags: ["tabs", "navigation"],
  }),
  component({
    id: "desktop.common.dialog",
    name: "Dialog and Sheet",
    summary: "Operates application-owned modal dialogs and macOS sheets.",
    kind: "common",
    sideEffectLevel: "reversible",
    requiredCapabilities: ["ui.inspect", "ui.invoke", "ui.wait"],
    actions: [action("confirm", "Confirm the current dialog."), action("cancel", "Cancel the current dialog."), action("dismiss", "Dismiss a non-decision dialog.")],
    assertions: ["isPresented", "hasTitle", "hasMessage"],
    locatorKeys: ["dialog.root", "dialog.confirm", "dialog.cancel"],
    tags: ["modal", "dialog"],
  }),
  component({
    id: "desktop.common.alert",
    name: "Application Alert",
    summary: "Reads and responds to application-owned alerts.",
    kind: "common",
    sideEffectLevel: "reversible",
    requiredCapabilities: ["ui.inspect", "ui.invoke"],
    actions: [action("chooseAction", "Choose a declared alert action."), action("cancel", "Cancel the alert.")],
    assertions: ["isPresented", "hasMessage", "actionIsAvailable"],
    locatorKeys: ["alert.root", "alert.action"],
    tags: ["alert", "modal"],
  }),
  component({
    id: "desktop.common.form",
    name: "Form",
    summary: "Fills and validates labeled native form controls.",
    kind: "common",
    sideEffectLevel: "writesLocal",
    requiredCapabilities: ["ui.inspect", "ui.invoke", "ui.set-value"],
    actions: [action("setField", "Set a labeled form value.", "writesLocal"), action("toggle", "Toggle a checkbox or switch.", "writesLocal"), action("submit", "Submit the form.", "writesLocal")],
    assertions: ["fieldHasValue", "fieldIsEnabled", "validationIsShown"],
    locatorKeys: ["form.root", "form.field", "form.submit"],
    tags: ["form", "input"],
  }),
  component({
    id: "desktop.common.text-editor",
    name: "Text Editor",
    summary: "Edits single-line, multiline, and rich text surfaces semantically.",
    kind: "common",
    sideEffectLevel: "writesLocal",
    requiredCapabilities: ["ui.inspect", "ui.set-value", "keyboard.inject"],
    actions: [action("replaceText", "Replace editor contents.", "writesLocal"), action("typeText", "Type into the editor.", "writesLocal"), action("selectAll", "Select all editor contents.", "reversible")],
    assertions: ["hasText", "isEditable", "hasSelection"],
    locatorKeys: ["editor.root", "editor.content"],
    tags: ["text", "input"],
  }),
  component({
    id: "desktop.common.search",
    name: "Search",
    summary: "Runs in-app searches and verifies their result state.",
    kind: "common",
    sideEffectLevel: "reversible",
    requiredCapabilities: ["ui.inspect", "ui.set-value", "ui.wait"],
    actions: [action("query", "Enter a search query."), action("clear", "Clear the current query."), action("selectResult", "Select a search result.")],
    assertions: ["queryEquals", "hasResults", "showsNoResults"],
    locatorKeys: ["search.field", "search.results", "search.result"],
    tags: ["search", "collection"],
  }),
  component({
    id: "desktop.common.collection",
    name: "List, Table, and Tree",
    summary: "Queries and selects rows, cells, list items, and tree nodes.",
    kind: "common",
    sideEffectLevel: "reversible",
    requiredCapabilities: ["ui.inspect", "ui.invoke"],
    actions: [action("selectItem", "Select a semantic collection item."), action("expandItem", "Expand a hierarchical item."), action("activateItem", "Activate a collection item.")],
    assertions: ["hasItem", "itemIsSelected", "itemCountEquals"],
    locatorKeys: ["collection.root", "collection.item"],
    tags: ["list", "table", "tree"],
  }),
  component({
    id: "desktop.common.context-menu",
    name: "Context Menu",
    summary: "Opens and invokes contextual commands for a semantic target.",
    kind: "common",
    sideEffectLevel: "reversible",
    requiredCapabilities: ["ui.inspect", "ui.invoke", "pointer.inject"],
    actions: [action("open", "Open the target context menu."), action("invokeItem", "Invoke a contextual command."), action("dismiss", "Dismiss the context menu.")],
    assertions: ["itemExists", "itemIsEnabled"],
    locatorKeys: ["context.target", "context.menu", "context.item"],
    tags: ["menu", "pointer"],
  }),
  component({
    id: "desktop.common.command-palette",
    name: "Command Palette",
    summary: "Opens, searches, and executes app command-palette entries.",
    kind: "common",
    sideEffectLevel: "reversible",
    requiredCapabilities: ["ui.inspect", "ui.set-value", "keyboard.inject"],
    actions: [action("open", "Open the command palette."), action("search", "Filter available commands."), action("execute", "Execute a matched command.")],
    assertions: ["isOpen", "commandExists", "commandIsSelected"],
    locatorKeys: ["commandPalette.root", "commandPalette.search", "commandPalette.command"],
    tags: ["commands", "keyboard"],
  }),
  component({
    id: "desktop.common.web-view",
    name: "Web View",
    summary: "Verifies a web surface and hands its DOM work to an explicit browser backend.",
    kind: "common",
    sideEffectLevel: "readOnly",
    requiredCapabilities: ["ui.inspect", "browser.dom.inspect"],
    actions: [
      action("requireLoaded", "Require the native web surface to expose a loaded document.", "readOnly"),
      action("bridgeToBrowserBackend", "Bind the declared web surface to an owned browser session.", "readOnly", ["browser.dom.inspect"]),
    ],
    assertions: ["isLoaded", "hasDocument", "bridgeIsAvailable"],
    locatorKeys: ["webView.root", "webView.document"],
    tags: ["webview", "browser", "dom"],
  }),
] as const;
