import { action, component } from "./helpers.js";

export const systemComponents = [
  component({
    id: "desktop.system.open-save-panel",
    name: "Open and Save Panel",
    summary: "Handles macOS open/save panels and Windows common item dialogs.",
    kind: "system",
    sideEffectLevel: "writesLocal",
    requiredCapabilities: ["ui.inspect", "ui.invoke", "system.open-save-panel"],
    actions: [action("choosePath", "Choose a file or directory.", "writesLocal"), action("saveToPath", "Choose a destination path.", "writesLocal"), action("cancel", "Cancel the system panel.", "reversible")],
    assertions: ["isPresented", "pathIsSelected", "fileTypeIsAllowed"],
    locatorKeys: ["filePanel.root", "filePanel.path", "filePanel.confirm"],
    tags: ["filesystem", "dialog"],
  }),
  component({
    id: "desktop.system.clipboard",
    name: "Clipboard",
    summary: "Reads and writes the platform clipboard under an explicit policy gate.",
    kind: "system",
    sideEffectLevel: "writesLocal",
    requiredCapabilities: ["clipboard.read", "clipboard.write"],
    actions: [action("readText", "Read clipboard text.", "readOnly"), action("writeText", "Replace clipboard text.", "writesLocal"), action("restore", "Restore captured clipboard state.", "reversible")],
    assertions: ["hasText", "isEmpty"],
    locatorKeys: [],
    tags: ["clipboard", "system-state"],
  }),
  component({
    id: "desktop.system.keyboard-shortcut",
    name: "Keyboard Shortcut",
    summary: "Sends semantic key chords with adapter-specific modifier mapping.",
    kind: "system",
    sideEffectLevel: "reversible",
    requiredCapabilities: ["keyboard.inject"],
    actions: [action("press", "Press a semantic keyboard shortcut."), action("pressSequence", "Press an ordered shortcut sequence.")],
    assertions: ["shortcutIsDeclared"],
    locatorKeys: [],
    tags: ["keyboard", "input"],
  }),
  component({
    id: "desktop.system.drag-drop",
    name: "Drag and Drop",
    summary: "Performs native drag-and-drop between semantic source and target elements.",
    kind: "system",
    sideEffectLevel: "writesLocal",
    requiredCapabilities: ["ui.inspect", "pointer.inject", "drag-drop.perform"],
    actions: [action("drag", "Drag one element to another.", "writesLocal"), action("dragFile", "Drag a declared file into the app.", "writesLocal")],
    assertions: ["sourceExists", "targetAcceptsDrop", "dropCompleted"],
    locatorKeys: ["drag.source", "drag.target"],
    tags: ["pointer", "filesystem"],
  }),
  component({
    id: "desktop.system.status-area",
    name: "Menu Bar and System Tray",
    summary: "Inspects macOS menu-bar extras and the Windows notification area.",
    kind: "system",
    sideEffectLevel: "reversible",
    requiredCapabilities: ["system.status-area.inspect", "ui.invoke"],
    actions: [action("openItem", "Open a status-area item."), action("dismiss", "Dismiss its popover or menu.")],
    assertions: ["itemExists", "itemIsVisible", "menuIsOpen"],
    locatorKeys: ["statusArea.item", "statusArea.menu"],
    tags: ["macos-menu-bar", "windows-system-tray"],
  }),
  component({
    id: "desktop.system.dock-taskbar",
    name: "Dock and Taskbar",
    summary: "Observes and invokes application items in the macOS Dock or Windows taskbar.",
    kind: "system",
    sideEffectLevel: "reversible",
    requiredCapabilities: ["ui.inspect", "ui.invoke"],
    actions: [action("activateApp", "Activate an application item."), action("openJumpMenu", "Open a Dock or taskbar item menu.")],
    assertions: ["appItemExists", "appIsRunning", "appIsActive"],
    locatorKeys: ["desktopShelf.app", "desktopShelf.menu"],
    tags: ["macos-dock", "windows-taskbar"],
  }),
  component({
    id: "desktop.system.permission-consent",
    name: "Permission Consent",
    summary: "Observes TCC or Windows privacy consent without silently granting access.",
    kind: "system",
    sideEffectLevel: "securitySensitive",
    requiredCapabilities: ["system.permission.inspect"],
    actions: [action("inspect", "Inspect the current permission state.", "readOnly"), action("request", "Trigger the app-owned permission request.", "securitySensitive"), action("cancel", "Cancel a visible consent flow.", "reversible")],
    assertions: ["stateEquals", "promptIsVisible", "settingsLinkExists"],
    locatorKeys: ["permission.prompt", "permission.cancel", "permission.settings"],
    tags: ["macos-tcc", "windows-privacy", "security"],
  }),
  component({
    id: "desktop.system.elevation-authorization",
    name: "Elevation and Authorization",
    summary: "Detects macOS authorization dialogs and Windows UAC secure-desktop prompts.",
    kind: "system",
    sideEffectLevel: "securitySensitive",
    requiredCapabilities: ["system.elevation.observe"],
    actions: [action("observe", "Observe whether elevation was requested.", "readOnly"), action("cancel", "Cancel when the backend can safely do so.", "reversible")],
    assertions: ["requestWasShown", "requestWasNotShown", "requiresManualHandling"],
    locatorKeys: ["elevation.prompt", "elevation.cancel"],
    tags: ["macos-authorization", "windows-uac", "security"],
  }),
] as const;
